### ISSUE TITLE
Should gaps be permitted in Kmers?

### ISSUE THREAD

**Issue by SabrinaJaye** [BioJulia/Kmers.jl#11]
Originally they were not, and for my purposes - e.g. genome assembly from raw reads, we don't expect to see them.
But I could see applications where they are wanted, e.g. if we allow 4-bit DNA kmers, variation analysis etc.

So my idea is this:

- [x] Building a 2 bit kmer from a 2 bit long seq = straight forward, basically just taking the bits, putting them in the kmer.
- [x] Building a 2 bit kmer from a 4 bit seq = take nucs from 4 bit seq, encode, and put into kmer - skipping over any non 2-bit permitted chars until full.
- [x] Building a 4 bit kmer from a 4 bit seq = take bits from seq and put in kmer - so allow all characters.
- [x] Building a 4 bit seq from a 2 bit seq = just take nucs, recode as 4 bits, put into kmer.

How does this sound?

**Comment by kescobo** [comment]
I don't have a strong intuition here - my naive understanding was that kmers were most computationally useful since you don't have to worry about gaps - if it doesn't match, it doesn't match. But if there are use-cases for it, would be awesome to have the flexibility. 

Perhaps just make the gapped versions really hard to make by accident (eg have everything default to 2 bit or error, unless the gaps are explicitly asked for)?

**Comment by SabrinaJaye** [comment]
So if you use the shorthand aliases for Kmers, lets say `DNAKmer{31}(seq)`, where seq is a 4 bit sequence created with dna"", or read from a fasta file.  That would create a kmer using the 2-bit alphabet using the rules I set above, as the aliases for DNA and RNA kmers use the two-bit alphabets as default. To force a 4 bit alphabet you'd have to explicitly ask for it by fully specifiying the kmer type parameterization.

**Comment by jakobnissen** [comment]
I think yes, it does make sense. Most applications won't use them, and that's OK. That's why we have 2-bit alphabets! But It'd be nice if Kmers were simply stack-allocated generic `BioSequences` with statically-known lengths. That would also imply `AminoAcidAlphabet` kmers.

**Comment by SabrinaJaye** [comment]
Ok, so I'm starting to think that to vastly simplify the codebase and make the logic of kmer iteration clear.

We simply reduce things to iterating over Kmers{A} in LongSequence{A}.

This should make looping over kmer iterators a bit more optimizable - known lengths etc.

If you want Kmers with no ambiguous symbols - don't iterate over sequence types where ambiguous symbols are a possibility.

**Comment by jakobnissen** [comment]
While that is a nicer approach principally, most applications I know of takes the approach of skipping ambiguous kmers. That is to say, people who use the library probably want functionality where non-ambiguous kmers are skipped.

That being said, it makes perfect sense to make a simpler iterator which just reads directly from the biosequence, and then another iterator which skips ambiguous symbols.

**Comment by SabrinaJaye** [comment]
I'm already going to be doing separate "canonical" iterators. So the case where the user just wants the kmers on the sequence going forward is much simpler.

**Comment by SabrinaJaye** [comment]
Either way, I think let's do simple first, get v0.1 and then go onwards.

**Comment by SabrinaJaye** [comment]
Ok So now we have the iterators generally enforcing alphabet consistency between longseq and kmer type,  but with exceptions to permit skipping for when kmers are DNA2 and the longseq is DNA4.
