### ISSUE TITLE
Various small issues

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/Kmers.jl#15]
A tracking list of small issues I encountered when using Kmers. I'll update it as I hit small bugs

* `@mer_str` does not work because `remove_newlines` is not defined.
* Slicing kmers does not work

Edit: Slicing kmers is type unstable, I know. But I was faced with the problem of counting all kmers beginning with `AAAAAA`, and suddenly found that very, very awkward. We could at least try it, and see if Julia's excellent contant propagation will make it type stable in practise when the slice is a constant.

**Comment by SabrinaJaye** [comment]
We can also do something slice-like but with type values if constant prop does not do it, e.g. kmer[Val(1:5)]
