### ISSUE TITLE
Implement a Cuckoo filter

### ISSUE THREAD

**Issue by kdm9** [BioJulia/Kmers.jl#4]
[see the paper](https://www.cs.cmu.edu/~dga/papers/cuckoo-conext2014.pdf)

**Comment by jakobnissen** [comment]
@kdmurray91 I implemented a Cuckoo filter some time ago: https://github.com/jakobnissen/Probably.jl . It's pretty fast, but might need some more testing if you want to include it in this package.

**Comment by jakobnissen** [comment]
I think we should not implement this here, but rather restrict this repo to only contain the kmer type, simple transformations on the kmers like reverse complement or translation, and kmer iterators. So I think we should close this issue

@SabrinaJaye any thoughts?

**Comment by jakobnissen** [comment]
Closing this as out-of-scope
