### ISSUE TITLE
⚠️ Is this package still maintained? ⚠️ 

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/Kmers.jl#7]
We are in the process of cleaning up unmaintained packages from the BioJulia repo. Unmaintained repositories can be harmful to the ecosystem for several reasons:

* They reduce the findability of working packages
* Users may accidentally install an unmaintained package and be frustrated when it doesn't work
* In contributes to an impression that BioJulia is poorly maintained.

__Is this package in a currently in a workable state with the newest version of Julia, and maintained by at least one dedicated maintainer?__

If so, __simply reply to this issue that you are the maintainer_, and we will close this issue. If not, we will make a pull request in approximately one month that changes the README and documentation to clearly state is it unmaintained. After yet another month, we will merge the PR, and archive the package.

**Comment by BenJWard** [comment]
Hey @jakobnissen, this package was I think largely unmaintained, buuut, I saw on the chat around spring cleaning for v3, that there was a desire to reduce the number of sequence types in BioSequences.jl such that it say defines the interfaces and generic methods, and provides one reference implementation, I guess LongSequence. If that is the case, I'm very happy to revitalise this package, with the new Kmer implementation I was working on in my BioSequences.jl PR.

**Comment by BenJWard** [comment]
Please see #8 which will bring this package up to date and maintained.

**Comment by jakobnissen** [comment]
Amazing - closing this issue!
